version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: react_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"  # Vite or 3000 for CRA
    command: ["npm", "run", "dev", "--", "--host"]

  sporebio_backend:
    build:
      context: ./backend
    image: sporebio_backend
